### ISSUE TITLE
Error: No '->' in first token of line 1 of --dose file

### ISSUE THREAD

**Issue by JiayiHelenZhou** [anb94/Canary#5]
Hi everyone, my group and I are working on converting genotypic imputation data (of Framingham Heart Study downloaded from dbGAP) from Mach/Minimac dosage format to plink binary bim.bed.fam format using Canary.  I am facing some challenges and would really appreciate your help!
__Overview of the imputed data downloaded from dbGaP:__
The chromosome-specific dosage files, “machout.chr[1-22]_c[1-2].dose.gz”, were formatted as below:
```
-No Header-
1001 DOSE 1.989 1.998 1.992 1.945 1.980 1.723 1.999 1.739 …

1002 DOSE 1.997 1.999 1.915 1.999 1.984 1.819 1.999 1.985 … 
```
,where 1001 and 1002 are example subject IDs of the participants.
The chromosome-specific info files, “machout.chr[1-22].info.gz”, were formatted as below:
```
SNP Al1 Al2 Freq1 MAF AvgCall Rsq Genotyped LooRsq EmpR EmpRsq Dose1 Dose2
19:80840:CCT_C R D 0.85939 0.14061 0.85939 0.00014 - - - - - -
19:90974 T C 0.99622 0.00378 0.99622 0.00007 - - - - - -
19:91106 C A 0.96355 0.03645 0.96355 0.00008 - - - - - -
```
__The challenge I am facing:__
I have been testing out Canary, for this dosage data conversion task, while Canary failed with an error at the last step of data conversion, which utilized a build-in dose2plink.
Canary does not accept my input dosage file “as-is”:
Canary expects the dosage file to have the following minimac format according to dose2plink (https://genepi.qimr.edu.au/staff/sarahMe/dose2plink.html):
```
 -no header-               
 F1->I1 DOSE 0.00 0.00 1.99 …  
 F2->I2 DOSE 1.01 0.00 0.99 …    
 F3->I3 DOSE 0.00 0.94 0.00 …    
```
Where the `->` token must be presented in the file.
As introduced before, the dosage files I am working with were started with subject IDs:
```
1001 DOSE 1.989 1.998 1.992 1.945 1.980 1.723 1.999 1.739 …

1002 DOSE 1.997 1.999 1.915 1.999 1.984 1.819 1.999 1.985 … 
```
Thus, Canary was terminated with the error message:
`Error: No '->' in first token of line 1 of --dose file.`
__My questions:__
1. Why Canary/dose2plink has to require the presence of `->` token? What dose it mean. In my data, the family IDs and individual IDs are the same. 
2. Is there any bypass to run Canary with my data "as-is"?
3. To resolve `Error: No '->' in first token of line 1 of --dose file.`, I intend to manually reformat the dosage data as below:
```
1001->1001 DOSE 1.989 1.998 1.992 1.945 1.980 …
 
1002->1002 DOSE 1.997 1.999 1.915 1.999 1.984 … 
```
However, I don’t know how to achieve this since 1) loading these data in R led to abortion of the R session, potentially due to large data sizes (5GB-20GB when compressed as .gz); 2) I did not find a way to reformat these dosage files directly in the Linux terminal without unzipping.
May I ask if manually reformatting the dosage data as I proposed is in the right direction for resolving the error that I encountered? If yes, how should I achieve it?

Thank you so much for reading this long post! This is my first time wrangling this type of genetic data, please forgive me if my questions are too junior. I shall be grateful for any insight you might have.

**Comment by anb94** [comment]
Hi,

Thank you for using our tool.


Sorry to hear that you are experiencing a problem, though we do have access to that dataset, we have not yet tried to use it with Canary. Could you please provide the version of the data that you have to see whether ours is the same?

If you want to edit your files manually I would recommend doing so with the command line, maybe with awk, rather than R. Maybe you can try extracting the first column and then pasting it to the start of the file again with the '->' in?

Best,

Adam
