### ISSUE TITLE
Converstion of dose/info file to vcf causing OOM error

### ISSUE THREAD

**Issue by akhilpampana** [anb94/Canary#6]
Hello,

I am attempting to convert the WHI dataset chromosome 18 imputed dataset to Plink format, but I encountered an "OOM" (Out of Memory) error. I tested this in a Slurm bash job with 400GB of RAM, yet the error persists. As the tutorial and tool were designed around WHI, I'm curious if this error has been encountered previously and how it was resolved.

Additionally, I'm interested in knowing if there's a method within Canary to subset the dose file into smaller chunks.

Thank you very much for your assistance, and I eagerly await your response.

Best regards,
Akhil

**Comment by anb94** [comment]
Hi,

Previously we had issues with memory when using the Perl version of the dose2plink tool that is why we used the C version of dose2plink developed by Christopher Chang in Canary. We didn't have any issues at the time, I will try to take a look at it soon to double check for you. Additionally you can take a look at the tool used for the conversion to see if anything there helps you [https://github.com/anb94/plink-ng/blob/master/1.9/dose2plink.c]

Best,

Adam

**Comment by akhilpampana** [comment]
Hello Adam,

Thank you so much for the response. I will look into the suggestion as mentioned. May I know what could be the possible reason for this issue in Perl script?

Regards
Akhil
